In [37]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [38]:
Data = pd.read_csv('Shuffled_Feature_MalwareGoodware_Unweighted.csv',header=None,low_memory=False)
le = LabelEncoder()
Data_encoded = Data.apply(le.fit_transform)
Data_encoded.head()

,0,1,2,3,4,5,6,7,8,9,...,4600,4601,4602,4603,4604,4605,4606,4607,4608,4609
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,1

In [56]:
Data_feature = Data_encoded.drop(Data_encoded.columns[4609],axis=1)

Result = Data_encoded[Data_encoded.columns[4609]]

#print(Data_feature.head())
#print("\n", Result.head())

In [55]:
Classifier = GaussianNB()

X_train, X_test, y_train, y_test = train_test_split(Data_feature, Result, test_size=0.3,random_state=109) #Split into Train and Test Set

Classifier.fit(X_train,y_train) # Train the Classifier using the training sets

Predicted_Result= Classifier.predict(X_test) #Predict Result
print(Predicted_Result)
#y_train.head(20)

[1 1 0 1 1 0 1 1 1 1 0 1 0 1 1 1 1 0 0 1 1 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1
 1 1 0 1 1 1 0 1 1 1 1 1 1 0 0 1 1 1 0 1 0 0 1 0 1 0 1 1 1 0 1 1 1 0 0 1 1
 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 1 1 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 0
 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 0 1 1 0 1
 1 1 0 1 0 1 1 1 0 1 1 1 0 1 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 0 1 1 1 0 1 1
 1 1 1 0 1 0 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 0
 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 0 1 1 0 1 1 1 0 1 0 1 1 0 1 1 1 1 1 1 0 1
 0 1 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 0 1 1 0 1 1]

189    1
808    1
715    1
896    0
293    0
649    1
700    0
674    1
449    1
310    0
611    1
52     0
867    0
327    1
429    1
192    0
684    1
513    0
219    0
71     1
Name: 4609, dtype: int64

In [57]:
Accuracy = metrics.accuracy_score(y_test, predicted)*100
print("Accuracy ====>>", Accuracy," %")

Accuracy ====>> 74.11347517730496  %